### ISSUE TITLE
perfectly working code solution

### ISSUE THREAD

**Issue by Zerbinati** [FireFather/stockfish-plus#6]
Hi Norman
here perfectly working code:
https://github.com/Zerbinati/stockfish-plus
change Bitboard.cpp
`    Bitboard occupancy[4096], reference[4096], edges, b;`
 `int epoch[4096] = {}, cnt = 0, size = 0;`  

base code start
https://github.com/FireFather/stockfish-plus/commit/ab57333a5df8f259baa5e345f9d51be14622e4ec

**Comment by FireFather** [comment]
Yes, I see my error now...
I'm also removing my 2 small changes from misc.cpp and search.cpp as well.

Thanks Marco
